import { db } from '@/lib/db'
import { NextRequest, NextResponse } from 'next/server'

export async function PATCH(request: NextRequest, { params }: { params: { id: string } }) {
  try {
    const id = params.id
    const body = await request.json()

    const data: any = {}
    const updatable = ['name','type','category','documentSubtype','issuingAuthority','documentNumber','expiryDate','status','isVerified','fileUrl']
    updatable.forEach((k) => {
      if (body[k] !== undefined) data[k] = body[k]
    })

    if (body.generateDocumentNumber) {
      // simple autogenerated doc number
      data.documentNumber = `DOC-${Date.now().toString().slice(-8)}`
    }

    if (data.expiryDate) data.expiryDate = new Date(data.expiryDate)

    const updated = await db.document.update({ where: { id }, data })
    return NextResponse.json(updated)
  } catch (error) {
    console.error('Update document error:', error)
    return NextResponse.json({ error: 'Failed to update document' }, { status: 500 })
  }
}

export async function DELETE(request: NextRequest, { params }: { params: { id: string } }) {
  try {
    const id = params.id
    await db.document.delete({ where: { id } })
    return NextResponse.json({ success: true })
  } catch (error) {
    console.error('Delete document error:', error)
    return NextResponse.json({ error: 'Failed to delete document' }, { status: 500 })
  }
}
